import { expect, test } from '@playwright/test'

test('P0: personal Workspace is implicit, navigation exposes work entries', async ({ page }) => {
  await page.goto('/workbench')
  const navigation = page.getByRole('navigation', { name: '员工工作台主导航' })
  // 历史对话与我的文件保留上下文入口和直达路由，不进入员工主导航。
  await expect(navigation.getByRole('button')).toHaveText(['新对话', 'Skill 广场', 'AI 同事', '团队空间', '自动任务'])
  await expect(page.getByLabel('选择工作空间')).toHaveCount(0)
  await expect(page.getByLabel('当前工作空间')).toHaveCount(0)
  await page.getByRole('button', { name: '添加内容' }).click()
  await expect(page.getByRole('menuitem', { name: '我的文件' })).toBeVisible()
  await navigation.getByRole('button', { name: 'Skill 广场', exact: true }).click()
  await expect(page.getByRole('navigation', { name: 'Skill 分类筛选' })).toBeVisible()
  const useSkill = page.getByRole('button', { name: /^使用 Skill：/ }).first()
  await expect(useSkill).toBeVisible()
  await useSkill.click()
  await expect(page).toHaveURL(/\/workbench\?skill=/)
  await expect(page.getByText('本次对话使用 Skill').or(page.getByText(/^@/))).toBeVisible()
  await navigation.getByRole('button', { name: 'AI 同事', exact: true }).click()
  await expect(page.getByLabel('AI 同事列表')).toBeVisible()
  const useAgent = page.getByRole('button', { name: /^与 AI 同事开始对话：/ }).first()
  await expect(useAgent).toBeVisible()
  await useAgent.click()
  await expect(page).toHaveURL(/\/workbench\?agent=/)
  await expect(page.getByLabel('已选择 AI 同事', { exact: true })).toBeVisible()
  await navigation.getByRole('button', { name: '团队空间', exact: true }).click()
  await expect(page.getByRole('heading', { name: '团队空间', exact: true })).toBeVisible()
  await expect(page.getByRole('button').filter({ hasText: '我的空间' })).toHaveCount(0)
  await navigation.getByRole('button', { name: '新对话', exact: true }).click()
  await expect(page.getByLabel('选择工作空间')).toHaveCount(0)
})

test('P0: legacy personal links redirect after the server authorizes the workspace', async ({ page }) => {
  const spaces = await page.request.get('/api/workbench/v1/workspaces')
  const personal = (await spaces.json()).data.find((row: { type: string }) => row.type === 'personal')
  expect(personal).toBeTruthy()
  await page.goto(`/workspaces/${personal.id}?tab=files`)
  await expect(page).toHaveURL(/\/files\?source=material$/)
  await expect(page.getByRole('heading', { name: '我的文件', exact: true })).toBeVisible()
  // P0 has no persistence; a clear capability error is intentional, never a fake successful file list.
  await expect(page.getByRole('alert').filter({ hasText: '不可用' })).toBeVisible()
  await page.goto('/workspaces/ws-personal-nonexistent')
  await expect(page.getByText('工作空间不存在或你没有访问权限', { exact: true })).toBeVisible()
  await expect(page).toHaveURL(/ws-personal-nonexistent$/)
})
